### ISSUE TITLE
Q about Tab.2

### ISSUE THREAD

**Issue by TwiceMao** [EastbeanZhang/Gaussian-Wild#6]
@EastbeanZhang 
Thx for your work. Why are the NeRF-W data listed in your Table 2 different from those in the original NeRF-W paper and lower than those reported by others?

**Comment by EastbeanZhang** [comment]
I presume you mean Table 1. We achieved similar results to CRNeRF using the non-official NeRF-W implementation at https://github.com/kwea123/nerf_pl, and thus, we've adopted CRNeRF(R/2) evaluation metrics.
