### ISSUE TITLE
Cannot find the train/test split from NeRF-W. Can the train/test split be arbitrary?

### ISSUE THREAD

**Issue by kevintsq** [EastbeanZhang/Gaussian-Wild#7]
Thanks for your great work! After visiting the NeRF-W page, I cannot find download links for the `.tsv` files. Can the train/test split be arbitrary?

**Comment by staydl30** [comment]
You can download the .tsv file at the bottom of this link [https://nerf-w.github.io/]. The training and testing splits can be arbitrary, but we suggest following the NeRF-W split method. They have filtered the dataset's images to remove low-quality images consisting largely of transient objects.

**Comment by kevintsq** [comment]
Oh, I found those links. Thanks!

**Comment by GopiRajuMatta** [comment]
How to prepare this for a custom dataset?
